### ISSUE TITLE
Test keeps spinning after test run

### ISSUE THREAD

**Issue by TFTomSun** [formulahendry/vscode-dotnet-test-explorer#211]
When I run NUnit based tests the test status keeps spinning after the test run. Is that a known issue? It was working before, but I didn't use vscode for quite a while (about 4 months)
![image](https://user-images.githubusercontent.com/5387192/56736895-99bc6b00-6769-11e9-8981-b7206d5c6898.png)

**Comment by goflyapig** [comment]
I hit this, too, and it looks like it's due to this breaking change (or bug) in newer versions of the SDK: https://github.com/Microsoft/vstest/issues/1951

**Comment by SupinePandora43** [comment]
same issue(

**Comment by stefanforsberg** [comment]
@TFTomSun Have you verified that vscode has the correct rights to the folder the results file is created in?

**Comment by alexc155** [comment]
Same for me. If I run on a mac with dotnet SDK 2.2.204 it spins. If I run on a PC with the same SDK it's fine. If I use SDK 2.2.107 it's fine everywhere. I think it's due to the warning on https://dotnet.microsoft.com/download/dotnet-core/2.2 about 2.2.204 on a mac.

Solution - downgrade to SDK 2.2.107 for now

**Comment by stefanforsberg** [comment]
@alexc155 Thank you for that clarification!

**Comment by vinaychandra** [comment]
@stefanforsberg I can confirm that this error occurs on Windows using dotnet version 2.2.300. Is there any progress on this?

**Comment by stefanforsberg** [comment]
@vinaychandra I just upgraded to 2.2.300 and I can't reproduce it. It's very hard to troubleshoot something that I can't reproduce so any help in that regards would be a great help.

**Comment by vinaychandra** [comment]
I can see the trx file being created as expected and pretty sure VS Code has permission for that folder.

This is my logs in Test Explorer.

```
Executing dotnet build in e:/(redacted)/Common.UnitTest
Executing dotnet test --no-build --logger "trx;LogFileName=E:\temp\test-explorer-SQjbN4\0.trx" --filter "FullyQualifiedName=(redacted).OperationTracing" in e:/(redacted)/Common.UnitTest
Process 30884 started
Test run for e:\(redacted)\Common.UnitTest\bin\Debug\net462\(redacted).Common.UnitTest.dll(.NETFramework,Version=v4.6.2)
Microsoft (R) Test Execution Command Line Tool Version 16.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
WARNING: Overwriting results file: E:\temp\test-explorer-SQjbN4\0.trx
Results File: E:\temp\test-explorer-SQjbN4\0.trx

Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 1.7214 Seconds

Process 30884 finished
```

This is the output but the progress bar keeps spinning. I do not see any result over the function name even.

![image](https://user-images.githubusercontent.com/5670927/58207949-99e05580-7c98-11e9-994f-e66aaa73532b.png)

![image](https://user-images.githubusercontent.com/5670927/58207966-a19ffa00-7c98-11e9-9781-f170e9d35c4a.png)

**Comment by SupinePandora43** [comment]
same results with xUnit

**Comment by stefanforsberg** [comment]
@vinaychandra Can you try to open this project in your vscode and try and run it's test? Does it behave in the same way with the never ending spinner then?

https://github.com/formulahendry/vscode-dotnet-test-explorer/tree/master/test/xunittests

**Comment by SupinePandora43** [comment]
@stefanforsberg https://github.com/formulahendry/vscode-dotnet-test-explorer/issues/203#issuecomment-481755426 this works for me!

**Comment by matthew798** [comment]
Unfortunately I have this problem and none of the fixes seem to do it..
Microsoft (R) Test Execution Command Line Tool Version 16.0.1
Copyright (c) Microsoft Corporation.  All rights reserved.

> 
> Starting test execution, please wait...
> Results File: /tmp/test-explorer-pDfTmi/0_2019-06-01_12-33-41-214.trx
> 
> Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
> Test Run Successful.
> Test execution time: 3.3049 Seconds
> 
> Process 6264 finished

Yet the test is still spinning.

I have set Test Project Path = `*.Tests/*.Tests.csproj`
I am using dotnet core sdk `3.0.0+100+preview.011568-1` but I get the same issue with `2.2.3+105-1`

**Comment by alexc155** [comment]
Happily whatever was broken for me in SDK 2.2.204 seems to have been fixed in SDK 2.2.300

:-)

**Comment by stefanforsberg** [comment]
@matthew798 We have a new release coming soon that adds a bit of logging which hopefully can help me figure out this issue. I'll get back to you when it's released.

**Comment by PiotrJustyna** [comment]
Any news? Can't get it working on my machine:

* netcoreapp3.0
* macos 10.14.5
* code 1.35.1

Log:

```bash
Test run for , expecting 1 test results file(s) in total
Executing dotnet build in [code path]
Executing dotnet test --no-build --logger "trx;LogFileName=/var/folders/gm/qplnfxrd75783gmjx0s_2s6w0000gr/T/test-explorer-OjerVg/0.trx" in [code path]
Process 27478 started
Process 27478 finished
```

Log folder given by the command above is empty and running `dotnet test` directly does return expected results.

**Comment by stefanforsberg** [comment]
@PiotrJustyna I get the same behaviour on mac with the latest sdk (v3.0.100-preview6) but it works with the latest stable version (2.2.300). On windows v3.0.100-preview6 works as expected. 

A bit further up people were having issues with specific versions of the sdk on mac so I'm inclined to think that something similar is happening here.

**Comment by PiotrJustyna** [comment]
@stefanforsberg Thanks for your comment. I tried downgrading to 2.2.300, but still getting the same problem. I guess I just use the terminal to run my tests until this gets fixed (whatever it is that's causing the issue).

**Comment by stefanforsberg** [comment]
@PiotrJustyna That's weird, I run a different mac os version than you but that seems highly unlikely to cause issues with this. Did you verify that the downgrade took effect (eg it's listed correctly when executing dotnet --version)?

**Comment by PiotrJustyna** [comment]
@stefanforsberg Yup. Uninstalled all versions I don't use, so now I just have 2.2.300 and 3.0 preview 6. Not a biggie, though. I can live without it for a while longer.

**Comment by stefanforsberg** [comment]
@PiotrJustyna I understand! 

I do think that if you have 3.0 still installed that would still be the default one used, if it's not too much trouble could you perhaps verify that by doing a dotnet --version in your terminal?

**Comment by PiotrJustyna** [comment]
@stefanforsberg I still have the 3.0 installed, had to keep it for other projects:

```bash
3.0.100-preview6-012264
```

I'd expect the runner takes the version used by the test project (and not the latest available), would that not be a correct assumption?

**Comment by stefanforsberg** [comment]
@PiotrJustyna We just execute dotnet test commands internally so whatever SDK that command points to (it defaults to the latest one installed) that's what's being used.

**Comment by timjroberts** [comment]
Not sure how useful this is, but if I run the `dotnet test` command that is issued by the extension, e.g., `dotnet test --no-build --logger "trx;LogFileName=/var/folders/tq/d3_cnp0903db5g117f9pzkfw0000gn/T/test-explorer-OSFCUY/0.trx" --filter "FullyQualifiedName=<redacted>"`

Then I see the following error:
```
Access to the path '/var/folders/tq/d3_cnp0_2019-08-15_08-16-42-51690_2019-08-15_08-16-42-5163db5g117f9pzkfw0_2019-08-15_08-16-42-5160_2019-08-15_08-16-42-5160_2019-08-15_08-16-42-5160_2019-08-15_08-16-42-516gn/T/test-explorer-OSFCUY' is denied.
```
This probably explains why the test keeps spinning in the Test Explorer window. It never gets the result file but the process has ended as reported.

**Comment by Muchiachio** [comment]
I have debugged the extension and got the same issue as Tim, access denied on the result file.
In particular [this line](https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/0903d11bbaa5684a06d4ebb8d87064325843f3f4/src/testResultsFile.ts#L77) sometimes fails the error check with `EBUSY: resource busy or locked, open 'C:\Users\MUCHIA~1\AppData\Local\Temp\test-explorer-OZRUGz\0.trx'` and there is no reject path so it's getting stuck until you restart visual studio code.

**Comment by rodolphocastro** [comment]
I had a similar issue under Windows environment.

Running VSCode as *Administrator* and having plenty of Xunit's `[Fact(DisplayName="Yaddah Yaddah")]` was the issue, at least for me.

The following log was being shown:
```
Test run for , expecting 2 test results file(s) in total
Executing dotnet build in c:/Repos/MyProject/tests/Tests.Unit.Api
Executing dotnet test --no-build --logger "trx;LogFileName=C:\Users\RODOLP~1\AppData\Local\Temp\test-explorer-6lx7Uv\0.trx" in c:/Repos/MyProject/tests/Tests.Unit.Api
Process 6504 started
New test results file
Parsed 1/2 file(s)
Process 6504 finished
Executing dotnet build in c:/Repos/ARDC.DevHelper.Backend/tests/Tests.Unit.Domain
Executing dotnet test --no-build --logger "trx;LogFileName=C:\Users\RODOLP~1\AppData\Local\Temp\test-explorer-6lx7Uv\1.trx" in c:/Repos/MyProject/tests/Tests.Unit.Domain
Process 5040 started
Process 5040 finished
```

The first part (running as admin) made a mess for the extension to get the correct permissions to R/W the trx files.

The second part seemed to make running all tests at the same test hang with the Spinning indicator. Removing all the DisplayNames solved the issue to me.

**Comment by Eulinky** [comment]
Experience the same problem on Mac OS Catalina. I suspect the chokidar file watcher is not notified about new files in the test result directory. However if I set the polling option to true, everythings works as expected. 

When I run a test node app (v10, v12) with chokidar, it works as expected.

Someone has an idea why chokidar does not get notified about an added file when running in the vs code extension host?

**Comment by djj0809** [comment]
I'm still facing this issue on Windows, no luck currently...

**Comment by alallo** [comment]
I have got the same issue. I'm on a Mac with Catalina 10.15.2 and .Net Core 2.2.207.
This is outoput after trying to run some tests:
`Executing dotnet test -t -v=q in /Users/alessandro/Repos/Project/myProject/MyProject1.Tests
Executing dotnet test -t -v=q in /Users/alessandro/Repos/Project/myProject/MyProject2.Tests
Executing dotnet test -t -v=q in /Users/alessandro/Repos/Project/myProject/MyProject3.Tests
Executing dotnet test -t -v=q in /Users/alessandro/Repos/Project/myProject/MyProject4.Tests
Test run for MyProject1.ListExtensionsTests, expecting 1 test results file(s) in total
Executing dotnet build in /Users/alessandro/Repos/Project/myProject/MyProject1.Tests
Executing dotnet test --no-build --logger "trx;LogFileName=/var/folders/65/9tvfp_gx1z5f7wn8l9697d6m0000gp/T/test-explorer-AosHNc/0.trx" --filter "FullyQualifiedName~MyProject1.ListExtensionsTests" in /Users/alessandro/Repos/Project/myProject/MyProject1.Tests
Process 28746 started
Process 28746 finished`

**Comment by fuzzzerd** [comment]
I began having this issue when my project went from a single test project to multiple. While the discovery works as expected, running the tests just leaves the extension in the spinning state indefinitely.

If I monitor the Test Explorer (test run output) I see all my tests run and pass. While monitoring the Test Explorer output, I see all the processes finish, but it never actually processes the trx files. Hitting the stop button does successfully reset things, but running the tests again results in the same behavior. 

I am on Windows 10, and my test projects are netcoreapp3.1.

**Comment by ps2goat** [comment]
I have similar issues. I have a solution within vscode, and multiple test projects under that. My current project is netcore 2., and my latest sdk for that is 2.2.301. My latest sdk version overall is 3.1.101.

I have Windows 10 with the 1909 update.

Even when I run a single test, the spinner never stops. The log output shows that a process starts and finishes successfully, and the trx file indicates success, but the extension won't update from a spinner to the test result.

**Comment by duyn9uyen** [comment]
I'm on a Mac (Catalina), .NET Core 3.1, with xUnit tests.  I don't seem to have any success running the tests from the explorer interface. I also don't see any output. Just spins.

**Comment by William-Froelich** [comment]
Same for me. Mac (Catalina) Net Core 3.1 .

One of my projects will always report results while the rests spin indefinitely. Even executing just one test from on of the non-reporting projects won't succeed. Looking at the output, it looks like even when running one test the output gets overwritten repeatedly

Could this issue be solved by using a different test report for each project instead of one for the whole solution?

`WARNING: Overwriting results file: /var/folders/y2/g32l6cw94_z00pgcjtc0pjnm0000gn/T/test-explorer-3JYgc1/0.trx
Results File: /var/folders/y2/g32l6cw94_z00pgcjtc0pjnm0000gn/T/test-explorer-3JYgc1/0.trx

WARNING: Overwriting results file: /var/folders/y2/g32l6cw94_z00pgcjtc0pjnm0000gn/T/test-explorer-3JYgc1/0.trx
Results File: /var/folders/y2/g32l6cw94_z00pgcjtc0pjnm0000gn/T/test-explorer-3JYgc1/0.trx

WARNING: Overwriting results file: /var/folders/y2/g32l6cw94_z00pgcjtc0pjnm0000gn/T/test-explorer-3JYgc1/0.trx
Results File: /var/folders/y2/g32l6cw94_z00pgcjtc0pjnm0000gn/T/test-explorer-3JYgc1/0.trx

WARNING: Overwriting results file: /var/folders/y2/g32l6cw94_z00pgcjtc0pjnm0000gn/T/test-explorer-3JYgc1/0.trx
Results File: /var/folders/y2/g32l6cw94_z00pgcjtc0pjnm0000gn/T/test-explorer-3JYgc1/0.trx`

**Comment by GeorchW** [comment]
Okay, so I have the same problem irregularly. [A comment above](https://github.com/formulahendry/vscode-dotnet-test-explorer/issues/211#issuecomment-522591881) has lead me to the lines where this seems to happen. I haven't debugged it by myself yet, but it seems that this is a race condition:

1. [When discovering tests](https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/0903d11bbaa5684a06d4ebb8d87064325843f3f4/src/testCommands.ts#L66), the test results folder is set up, [setting a callback on file added](https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/0903d11bbaa5684a06d4ebb8d87064325843f3f4/src/testCommands.ts#L172).
2. Later, when the tests are running, `dotnet test` (or its children) will open the results file and start writing to it.
3. If the test runner takes long enough to write the results file, the callback is activated before the file is written out completely.
4. The callback fails to parse the file, since it is incomplete or locked, resulting in a premature exit.
5. Since the callback is only invoked on file creation, it will be never invoked again. The circle keeps spinning forever.

The core issue is that, instead of first waiting for the child process to terminate, then read the produced results file, the results file is prematurely parsed. This is probably intended to enable displaying partially run tests, but may sometimes fail since a file may be written and simultaneously parsed. A solution would be to 

1. Set an additional handler on file change
2. Keep trying to parse a file if it failed to parse in the first try

I might open a PR later to try and fix this, not sure though.

**Comment by GeorchW** [comment]
Heh, okay, I'm pretty sure that I found the bug. When this happens, you can do the following (absurd) workaround: 

1. Open the Text Explorer log (Output -> Test Explorer)
2. Find the command that did not work out (usually the last one). It should be formatted like this: `dotnet test --no-build --logger "trx;LogFileName=<some temporary path>/0.trx`
3. Rename the file `<some temporary path>/0.trx` to `<some temporary path>/1.trx` The actual file name does not matter, it just needs to be different, such that a new file listener event is invoked.
4. TADA! - the checkmarks appear instantly.

**Comment by duyn9uyen** [comment]
@GeorchW, do you have to do that each time the test stalls or will this fix persist?

**Comment by GeorchW** [comment]
Nope, have to do this every time. By the way, here's an example that more reliably reproduces the issue: 
```
[TestCase(0)]
[TestCase(1)]
[TestCase(2)]
[TestCase(3)]
[TestCase(4)]
[TestCase(5)]
[TestCase(6)]
[TestCase(7)]
[TestCase(8)]
[TestCase(9)]
[TestCase(10)]
[TestCase(11)]
[TestCase(12)]
[TestCase(13)]
[TestCase(14)]
[TestCase(15)]
[TestCase(16)]
[TestCase(17)]
[TestCase(18)]
[TestCase(19)]
public void QuickTest(int dummy) { }
```

**Comment by fuzzzerd** [comment]
That's great! Any word on when this will make its way into a release?

**Comment by stefanforsberg** [comment]
@fuzzzerd I'll run the master version of extension at our mobstation at work for a day or two and see how it behaves. I'd also like to update the test projects in the extension to netcore 3.1 so we are more in sync with dotnet versions.

So if all looks well I'd guess later this week.

**Comment by GeorchW** [comment]
Nice! I'd suggest to update the extension dependencies, too; at least `npm audit fix` would be nice. Do you already have a plan on merging further PRs?

**Comment by stefanforsberg** [comment]
@GeorchW 0.7.8 is on it's way out now (as in I've told @formulahendry to release it) with what is in master now.

In the next release I'd like to get an audit fix as well as update the test projects to 3.1 as mentioned above. I have no immediate plans as for which PR will be merged yet.

If you have the time to look at the audit fix in a PR that would be nice. IIRC the update had a breaking change for something related to how we test the functionality to support mstest/nunit (which requires file parsing since they don't report FQN when run through dotnet test discovery). But it was over a year ago when I looked at that so my memory may fail me.

**Comment by GeorchW** [comment]
@stefanforsberg I've added a PR.

**Comment by stefanforsberg** [comment]
I'm curious to see how people experience are now that 0.7.2 is released. Any changes regarding the spinning people?

**Comment by fuzzzerd** [comment]
The solution I was struggling to run tests with, now works after the latest release. 

I have bumped into some issues with my output dlls being locked, but I have *not* been able to pinpoint that as related to the plugin. Just mentioning in case anyone else is noticing it too.

**Comment by ps2goat** [comment]
@stefanforsberg - Yes, this update works for me.

**Comment by ps2goat** [comment]
@stefanforsberg  This seems broken again after the release of 0.7.3. My extension auto-updated and started spinning again, with no results. I installed 0.7.2 and it worked.

One caveat: I haven't restarted VS Code in a while, and I'm probably only up to the April release at the moment.

**Comment by stefanforsberg** [comment]
@ps2goat That's unfortunate. Can't think of any direct reason why 0.7.3 would bring back the problem.

Would you mind testing installing 0.7.3 again and do a restart of vscode afterwards and give it another try?

Also could you paste how the log looks if the spinning persists?

**Comment by duyn9uyen** [comment]
I'm on the 0.7.3 plugin and with VS Code 1.46.1 (Mac/Catalina) and it seems to be working for me.

**Comment by ps2goat** [comment]
I did close all app instances and restart VS Code, and it updated to April 2020 1.45.1. Then I updated to the latest plugin v 0.7.3, and did a reload. Things appear to be working, so maybe there was a mismatch of versions between open VS Code instances.

Sorry for causing problems!
